---
# tasks file for vagrant(On Debian family)
- name: Download Vagrant package
  get_url: url="{{ vagrant_download_url }}" checksum="sha256:{{ vagrant_sha256 }}" dest="{{ vagrant_download_tmppath }}"
- name: Check whether Vagrant is installed.
  command: "dpkg-query -f '${Status}' -W vagrant"
  register: check_vagrant
  ignore_errors: yes
  changed_when: no
- name: Install Vagrant with dpkg
  apt: deb="{{ vagrant_download_tmppath }}"
  become: yes
  when: "'ok installed' not in check_vagrant.stdout"
